% 假设 names1 是 1×4 的 cell，存放 4 个指标名
%      names2 是 1×6 的 cell，存放 6 个方法名
names1 = {'ACC', 'NMI', 'ARI', 'FSC'}; 
names2 = {'kmodes', 'CDCDR', 'Het2Hom', 'CMS', 'ADC', 'COForest'};

% 创建 4×6 的紧凑网格，宽6cm，高7cm
fig = figure('Units','centimeters','Position',[0, 0, 6, 7]);
tl  = tiledlayout(4, 6, 'TileSpacing','compact', 'Padding','compact');

for i = 1:numel(names1)
    for j = 1:numel(names2)
        ax = nexttile((i-1)*numel(names2) + j);

        % —— 动态取数据 —— 
        x = evalin('base', sprintf('com_%s_%s(com_CMI_%s>0.5)', ...
             names1{i}, names2{j}, names2{j}));
        y = evalin('base', sprintf('com_%s_%s(com_CMI_%s<0.5)', ...
             names1{i}, names2{j}, names2{j}));

        % —— 箱线图（不显示离群点） —— 
        boxplot([x; y], [ones(size(x)); 2*ones(size(y))], ...
            'BoxStyle',    'outline', ...
            'Colors',      [0.9, 0.2, 0.2; 0.2, 0.6, 0.8], ...
            'MedianStyle', 'target', ...
            'Symbol',      '', ...
            'Widths',      0.6);

        % —— 坐标轴美化，仅加粗 X 轴标签 —— 
        set(ax, ...
            'FontName',   'Arial', ...
            'FontSize',   8, ...
            'FontWeight', 'normal', ...
            'XTickLabel', {'CMI>0.5','CMI<0.5'}, ...
            'TickLength', [0.02,0.02]);
        ax.XAxis.FontWeight = 'bold';   % 仅 X 轴标签加粗

        % —— 标题展示变量名 —— 
        title(ax, sprintf('%s (%s) @Validation', names1{i}, names2{j}), ...
            'FontName',   'Arial', ...
            'FontSize',   8, ...
            'FontWeight', 'bold');

        % —— 在图内空白处标注 p 值，p 斜体加粗，其它正常 —— 
        [p,~] = ranksum(x, y, 'tail','right');
        text(0.5, 0.90, ['\it p\rm = ' sprintf('%.1E', p)], ...
            'Units',             'normalized', ...
            'HorizontalAlignment','center', ...
            'FontName',          'Arial', ...
            'FontSize',          8, ...
            'Interpreter',       'tex');
    end
end